### ISSUE TITLE
Unhandled exception occurred in '3.1-stable'

### ISSUE THREAD

**Issue by Abdallah-Fouad-X** [commixproject/commix#543]
[info] Resolving hostname 'localhost'.
[info] Checking connection to the target URL.           
[warning] Swithing the '--is-admin' to '--is-root' because the target has been identified as unix-like. 
[warning] The provided value for GET parameter 'kira' is empty. Use valid values to run properly.
[info] A previously stored session has been held against that host.
Do you want to resume to the (results-based) classic command injection point? [Y/n] > y
[critical] Unhandled exception occurred in '3.1-stable'. It is recommended to retry your run with the latest (dev) version from official GitHub repository at 'https://github.com/commixproject/commix.git'. If the exception persists, please open a new issue at 'https://github.com/commixproject/commix/issues/new' with the following text and any other information required to reproduce the bug. The developers will try to reproduce the bug, fix it accordingly and get back to you.
Commix version: 3.1-stable
Python version: 3.8.5
Operating system: posix
Command line: commix.py -u *********************************** --is-admin

Traceback (most recent call last):
  File "commix.py", line 35, in <module>
    main()
  File "commix.py", line 30, in main
    import src.core.main
  File "main.py", line 907, in <module>
    main(filename, url)
  File "main.py", line 604, in main
    controller.do_check(url, filename)
  File "controller.py", line 684, in do_check
    perform_checks(url,filename)
  File "controller.py", line 608, in perform_checks
    basic_level_checks()
  File "controller.py", line 573, in basic_level_checks
    get_request(url, http_request_method, filename, timesec)
  File "controller.py", line 491, in get_request
    injection_proccess(url, check_parameter, http_request_method, filename, timesec)
  File "controller.py", line 216, in injection_proccess
    if cb_handler.exploitation(url, timesec, filename, http_request_method) != False:
  File "cb_handler.py", line 486, in exploitation
    if cb_injection_handler(url, timesec, filename, http_request_method) == False:
  File "cb_handler.py", line 102, in cb_injection_handler
    checks.check_for_stored_tamper(payload)
  File "checks.py", line 1045, in check_for_stored_tamper
    decoded_payload = recognise_payload(payload)
  File "checks.py", line 1021, in recognise_payload
    decoded_payload = payload.decode("hex")
AttributeError: 'str' object has no attribute 'decode'
Do you want to automatically create a new (anonymized) issue with the unhandled exception information at the official Github repository? [y/N]

**Comment by stasinopoulos** [comment]
Hello @Abdallah-Fouad-X could you please check with python 2.7?

**Comment by Abdallah-Fouad-X** [comment]
Hello @stasinopoulos , it work fine with python 2.7
