### ISSUE TITLE
crash for up to date commix

### ISSUE THREAD

**Issue by lacroutelacroute** [commixproject/commix#95]
hello  stasinopoulos

i run up to date version
crash after start

~$ sudo /usr/local/bin/commix -v 1 --url="https://********.********.co.za/ost/nsp/FrontOfficePublic/CustomErrors/?sb_ost_ltm="   --random-agent  --level=1   -p  sb_ost_ltm   --cookie="WASReqURL=https:///ost/sp/frontofficesecure/legacy/newframes.asp;JSESSIONID=00005pIR-MFC02CdzuFGkPEeg_r:-1;ASPSESSIONIDQWBBCTTB=OCNHNFNCNIDJAEJGBMOADKGG"  --technique="f"  --tamper="base64encode" --batch  --charset="utf-8" --all
[sudo] Mot de passe de fakessh : 
                                       __           
    ___   ___     ___ ___     ___ ___ /\_\   __  _   
  /`___\ / __`\ /' __` __`\ /' __` __`\/\ \ /\ \/'\  v2.0-stable
 /\ \__//\ \L\ \/\ \/\ \/\ \/\ \/\ \/\ \ \ \\/>  </  
 \ \____\ \____/\ \_\ \_\ \_\ \_\ \_\ \_\ \_\/\_/\_\ http://commixproject.com
  \/____/\/___/  \/_/\/_/\/_/\/_/\/_/\/_/\/_/\//\/_/ (@commixproject)

+--
Automated All-in-One OS Command Injection and Exploitation Tool
Copyright (c) 2014-2017 Anastasios Stasinopoulos (@ancst)
+--

[*] Checking connection to the target URL... Traceback (most recent call last):
  File "/pentest/exploitation/commix/commix.py", line 1045, in <module>
    response = url_response(url)
  File "/pentest/exploitation/commix/commix.py", line 164, in url_response
    response = examine_request(request)
  File "/pentest/exploitation/commix/commix.py", line 81, in examine_request
    headers.check_http_traffic(request)
  File "/pentest/exploitation/commix/src/core/requests/headers.py", line 136, in check_http_traffic
    opener.open(request)
  File "/usr/lib/python2.7/urllib2.py", line 429, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 447, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 1241, in https_open
    context=self._context)
AttributeError: connection_handler instance has no attribute '_context'

same command work with commix 1.9 stable
